# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/oatpp-starter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/oatpp-starter/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/oatpp-starter/build/CMakeFiles /opt/oatpp-starter/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/oatpp-starter/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my-project-test

# Build rule for target.
my-project-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my-project-test
.PHONY : my-project-test

# fast build rule for target.
my-project-test/fast:
	$(MAKE) -f CMakeFiles/my-project-test.dir/build.make CMakeFiles/my-project-test.dir/build
.PHONY : my-project-test/fast

#=============================================================================
# Target rules for targets named my-project-exe

# Build rule for target.
my-project-exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my-project-exe
.PHONY : my-project-exe

# fast build rule for target.
my-project-exe/fast:
	$(MAKE) -f CMakeFiles/my-project-exe.dir/build.make CMakeFiles/my-project-exe.dir/build
.PHONY : my-project-exe/fast

#=============================================================================
# Target rules for targets named my-project-lib

# Build rule for target.
my-project-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my-project-lib
.PHONY : my-project-lib

# fast build rule for target.
my-project-lib/fast:
	$(MAKE) -f CMakeFiles/my-project-lib.dir/build.make CMakeFiles/my-project-lib.dir/build
.PHONY : my-project-lib/fast

src/App.o: src/App.cpp.o

.PHONY : src/App.o

# target to build an object file
src/App.cpp.o:
	$(MAKE) -f CMakeFiles/my-project-exe.dir/build.make CMakeFiles/my-project-exe.dir/src/App.cpp.o
.PHONY : src/App.cpp.o

src/App.i: src/App.cpp.i

.PHONY : src/App.i

# target to preprocess a source file
src/App.cpp.i:
	$(MAKE) -f CMakeFiles/my-project-exe.dir/build.make CMakeFiles/my-project-exe.dir/src/App.cpp.i
.PHONY : src/App.cpp.i

src/App.s: src/App.cpp.s

.PHONY : src/App.s

# target to generate assembly for a file
src/App.cpp.s:
	$(MAKE) -f CMakeFiles/my-project-exe.dir/build.make CMakeFiles/my-project-exe.dir/src/App.cpp.s
.PHONY : src/App.cpp.s

src/controller/MyController.o: src/controller/MyController.cpp.o

.PHONY : src/controller/MyController.o

# target to build an object file
src/controller/MyController.cpp.o:
	$(MAKE) -f CMakeFiles/my-project-lib.dir/build.make CMakeFiles/my-project-lib.dir/src/controller/MyController.cpp.o
.PHONY : src/controller/MyController.cpp.o

src/controller/MyController.i: src/controller/MyController.cpp.i

.PHONY : src/controller/MyController.i

# target to preprocess a source file
src/controller/MyController.cpp.i:
	$(MAKE) -f CMakeFiles/my-project-lib.dir/build.make CMakeFiles/my-project-lib.dir/src/controller/MyController.cpp.i
.PHONY : src/controller/MyController.cpp.i

src/controller/MyController.s: src/controller/MyController.cpp.s

.PHONY : src/controller/MyController.s

# target to generate assembly for a file
src/controller/MyController.cpp.s:
	$(MAKE) -f CMakeFiles/my-project-lib.dir/build.make CMakeFiles/my-project-lib.dir/src/controller/MyController.cpp.s
.PHONY : src/controller/MyController.cpp.s

test/MyControllerTest.o: test/MyControllerTest.cpp.o

.PHONY : test/MyControllerTest.o

# target to build an object file
test/MyControllerTest.cpp.o:
	$(MAKE) -f CMakeFiles/my-project-test.dir/build.make CMakeFiles/my-project-test.dir/test/MyControllerTest.cpp.o
.PHONY : test/MyControllerTest.cpp.o

test/MyControllerTest.i: test/MyControllerTest.cpp.i

.PHONY : test/MyControllerTest.i

# target to preprocess a source file
test/MyControllerTest.cpp.i:
	$(MAKE) -f CMakeFiles/my-project-test.dir/build.make CMakeFiles/my-project-test.dir/test/MyControllerTest.cpp.i
.PHONY : test/MyControllerTest.cpp.i

test/MyControllerTest.s: test/MyControllerTest.cpp.s

.PHONY : test/MyControllerTest.s

# target to generate assembly for a file
test/MyControllerTest.cpp.s:
	$(MAKE) -f CMakeFiles/my-project-test.dir/build.make CMakeFiles/my-project-test.dir/test/MyControllerTest.cpp.s
.PHONY : test/MyControllerTest.cpp.s

test/tests.o: test/tests.cpp.o

.PHONY : test/tests.o

# target to build an object file
test/tests.cpp.o:
	$(MAKE) -f CMakeFiles/my-project-test.dir/build.make CMakeFiles/my-project-test.dir/test/tests.cpp.o
.PHONY : test/tests.cpp.o

test/tests.i: test/tests.cpp.i

.PHONY : test/tests.i

# target to preprocess a source file
test/tests.cpp.i:
	$(MAKE) -f CMakeFiles/my-project-test.dir/build.make CMakeFiles/my-project-test.dir/test/tests.cpp.i
.PHONY : test/tests.cpp.i

test/tests.s: test/tests.cpp.s

.PHONY : test/tests.s

# target to generate assembly for a file
test/tests.cpp.s:
	$(MAKE) -f CMakeFiles/my-project-test.dir/build.make CMakeFiles/my-project-test.dir/test/tests.cpp.s
.PHONY : test/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... my-project-test"
	@echo "... my-project-exe"
	@echo "... my-project-lib"
	@echo "... src/App.o"
	@echo "... src/App.i"
	@echo "... src/App.s"
	@echo "... src/controller/MyController.o"
	@echo "... src/controller/MyController.i"
	@echo "... src/controller/MyController.s"
	@echo "... test/MyControllerTest.o"
	@echo "... test/MyControllerTest.i"
	@echo "... test/MyControllerTest.s"
	@echo "... test/tests.o"
	@echo "... test/tests.i"
	@echo "... test/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

